# Building your first fully connected network and a CNN 

## Building a simple fully connected network (a Multi-Layer Perceptron)

Let's set up the paths and make a dataset again:

In [1]:
import os,sys
currentdir = os.getcwd()
parentdir = os.path.dirname(currentdir)
sys.path.insert(0,parentdir) 

In [2]:
from utils.data_handling import WCH5Dataset

Now Let's make our model. We'll talk about 
  - model parameters
  - inputs and the forward method
  - Modules containing modules
  - Sequential Module  
  Lets open [simpleMLP](/edit/models/simpleMLP.py)

In [3]:
from models.simpleMLP import SimpleMLP

In [4]:
model_MLP=SimpleMLP(num_classes=3)

Let's look at the parameters:

In [5]:
for name, param in model_MLP.named_parameters():
    print("name of a parameter: {}, type: {}, parameter requires a gradient?: {}".
          format(name, type(param),param.requires_grad))

name of a parameter: fc1.weight, type: <class 'torch.nn.parameter.Parameter'>, parameter requires a gradient?: True
name of a parameter: fc1.bias, type: <class 'torch.nn.parameter.Parameter'>, parameter requires a gradient?: True
name of a parameter: fc2.weight, type: <class 'torch.nn.parameter.Parameter'>, parameter requires a gradient?: True
name of a parameter: fc2.bias, type: <class 'torch.nn.parameter.Parameter'>, parameter requires a gradient?: True
name of a parameter: fc5.weight, type: <class 'torch.nn.parameter.Parameter'>, parameter requires a gradient?: True
name of a parameter: fc5.bias, type: <class 'torch.nn.parameter.Parameter'>, parameter requires a gradient?: True


As we can see by default the parameters have `requires_grad` set - i.e. we will be able to obtain gradient of the loss function with respect to these parameters.

Let's quickly look at the [source](https://pytorch.org/docs/stable/_modules/torch/nn/modules/linear.html#Linear) for the linear module

The parameters descend from the `Tensor` class. When `Parameter` object is instantiated as a member of a `Module` object class the parameter is added to `Module`s list of parameters automatically. This list and values are captured in the 'state dictionary' of a module:

In [6]:
model_MLP.state_dict()

OrderedDict([('fc1.weight',
              tensor([[ 2.6680e-03,  3.2562e-03, -3.4426e-03,  ...,  6.3970e-03,
                       -5.7259e-03, -4.4637e-03],
                      [ 1.7782e-03, -3.3476e-03,  1.1002e-03,  ...,  3.3208e-03,
                       -2.1068e-03, -5.4390e-03],
                      [ 1.5775e-05, -1.2682e-03,  3.8744e-03,  ..., -2.9397e-03,
                       -5.8011e-03,  3.6649e-03],
                      ...,
                      [-5.7130e-03, -8.6100e-04,  3.4296e-03,  ...,  8.1327e-04,
                        2.5296e-03,  3.6280e-04],
                      [ 3.7208e-04,  3.8775e-03, -2.4209e-03,  ...,  3.5177e-03,
                       -5.6878e-03,  1.8522e-03],
                      [ 4.8859e-03,  6.2634e-03, -2.9589e-03,  ..., -2.3155e-04,
                       -1.8440e-03,  5.8361e-03]])),
             ('fc1.bias',
              tensor([-2.5218e-03, -2.2686e-03, -2.4800e-03, -2.3030e-03,  5.7291e-03,
                       4.3988e-03,  2.9257e

Did you notice that the values are not 0? This is actually by design - by default that initialization follows an accepted scheme - but many strategies are possible

Now let's look at sequential version

In [7]:
from models.simpleMLP import SimpleMLPSEQ
model_MLPSEQ=SimpleMLPSEQ(num_classes=3)

In [8]:
for name, param in model_MLPSEQ.named_parameters():
    print("name of a parameter: {}, type: {}, parameter requires a gradient?: {}".
          format(name, type(param),param.requires_grad))

name of a parameter: _sequence.0.weight, type: <class 'torch.nn.parameter.Parameter'>, parameter requires a gradient?: True
name of a parameter: _sequence.0.bias, type: <class 'torch.nn.parameter.Parameter'>, parameter requires a gradient?: True
name of a parameter: _sequence.2.weight, type: <class 'torch.nn.parameter.Parameter'>, parameter requires a gradient?: True
name of a parameter: _sequence.2.bias, type: <class 'torch.nn.parameter.Parameter'>, parameter requires a gradient?: True
name of a parameter: _sequence.4.weight, type: <class 'torch.nn.parameter.Parameter'>, parameter requires a gradient?: True
name of a parameter: _sequence.4.bias, type: <class 'torch.nn.parameter.Parameter'>, parameter requires a gradient?: True
name of a parameter: _sequence.6.weight, type: <class 'torch.nn.parameter.Parameter'>, parameter requires a gradient?: True
name of a parameter: _sequence.6.bias, type: <class 'torch.nn.parameter.Parameter'>, parameter requires a gradient?: True
name of a parame

In [9]:
print(model_MLPSEQ.state_dict())

OrderedDict([('_sequence.0.weight', tensor([[ 2.8483e-03, -5.1011e-03, -2.7853e-04,  ...,  4.6351e-03,
          2.0244e-03, -4.6997e-03],
        [ 5.1449e-03,  2.9838e-03,  5.7291e-03,  ..., -5.7026e-03,
         -4.9322e-04,  3.8901e-03],
        [-1.9483e-03, -9.6000e-04, -5.0261e-03,  ..., -1.0807e-03,
         -3.5274e-03, -9.9408e-04],
        ...,
        [-5.8123e-03, -5.2416e-03,  1.6391e-03,  ...,  4.5877e-05,
         -6.2063e-03,  5.0585e-03],
        [-4.8052e-03, -5.0750e-03, -1.1928e-03,  ..., -3.5907e-03,
         -1.7558e-03,  6.1739e-03],
        [ 6.1718e-03,  1.5871e-03,  4.4793e-03,  ...,  2.8583e-03,
          8.3788e-04,  5.1749e-03]])), ('_sequence.0.bias', tensor([ 3.0710e-03, -4.4811e-03, -9.2219e-04,  5.0590e-03,  3.2422e-03,
         1.2470e-03, -5.0901e-03, -1.9904e-03,  4.1131e-04,  3.6846e-03,
         6.4616e-04, -1.3959e-03, -3.8742e-03,  8.9456e-04, -3.0524e-03,
        -2.4453e-03, -2.8221e-03, -2.9666e-03,  1.8713e-03,  3.6737e-03,
         4.1735e-

As we can see the parameters look similar but have different names

## Training a model

First let's make a dataset object

In [10]:
dset=WCH5Dataset("/scratch/fcormier/Public/NUPRISM.h5",reduced_dataset_size=100000,val_split=0.1,test_split=0.1)

Reduced size: 100000


Let's make a dataloader and grab a first batch

In [11]:
from torch.utils.data import DataLoader
from torch.utils.data.sampler import SubsetRandomSampler

train_dldr=DataLoader(dset,
                      batch_size=32,
                      shuffle=False,
                      sampler=SubsetRandomSampler(dset.train_indices))
train_iter=iter(train_dldr)

In [12]:
batch0=next(train_iter)

In [13]:
data=batch0[0]
labels=batch0[1]

Now compute the model output on the data

In [14]:
model_out=model_MLP(data)


In [15]:
print(labels)

tensor([2, 1, 0, 2, 2, 0, 1, 2, 2, 0, 1, 0, 2, 1, 2, 1, 1, 0, 0, 1, 1, 2, 1, 0,
        2, 1, 2, 2, 0, 0, 0, 0])


In [16]:
print(model_out)

tensor([[ 10.5870,  20.1918,  21.9317],
        [-12.2087,   7.7353,  12.2677],
        [-42.1053,  19.5736,  -2.9641],
        [-16.5042,   0.4974,  -7.8518],
        [ -1.9450,   5.5483,  -5.1083],
        [ -2.5612,   7.1446,  25.9561],
        [ -3.5834,  19.2639,  30.9361],
        [-74.8336,  17.4859, -25.8750],
        [-22.4322,  -7.6299, -13.1747],
        [-25.6413,   8.8435,   6.8586],
        [-20.1189,  -5.1615, -13.1563],
        [-58.6281,  27.3112,  44.7698],
        [  1.2991,  19.9859,  -8.3300],
        [-18.5540, -25.4850,  30.3851],
        [ -3.7894,   7.3229, -11.2501],
        [ -0.2566,  18.5016,  37.4023],
        [-36.6636,  11.8829, -31.3037],
        [-22.7839,  44.0696,  62.1200],
        [-60.5168, -30.5942,  17.6290],
        [-16.8623,  17.9748,   7.2353],
        [-31.2869, -13.7888, -13.3608],
        [ -4.4971,   2.4517,  -2.9462],
        [-31.2688,  -7.2606,  -0.9698],
        [  2.6306, -14.6262,  50.3731],
        [-15.1132,   8.6552,  -1.4031],


Now we have model's predictions and we above got 'true' labels from the dataset, so we can now compute the loss - CrossEntropyLoss is the apropropriate one to use here. We will use `CrossEntropyLoss` from `torch.nn` - btw it is also a `Module`. First create it:

In [17]:
from torch.nn import CrossEntropyLoss
loss_module=CrossEntropyLoss()

Now evaluate the loss. 

In [18]:
loss_tensor=loss_module(model_out,labels)

In [19]:
print(loss_tensor)

tensor(25.8749, grad_fn=<NllLossBackward0>)


This was a 'forward pass'. We should now have a computational graph available - let's plot it for the kicks...

In [20]:
#Can't get torchivz in compute canada
#from torchviz import make_dot
#make_dot(loss_tensor,params=dict(model_MLP.named_parameters()))

Before we calculate the gradients - let's check what they are now...

In [21]:
for name, param in model_MLP.named_parameters():
    print("name of a parameter: {}, gradient: {}".
          format(name, param.grad))

name of a parameter: fc1.weight, gradient: None
name of a parameter: fc1.bias, gradient: None
name of a parameter: fc2.weight, gradient: None
name of a parameter: fc2.bias, gradient: None
name of a parameter: fc5.weight, gradient: None
name of a parameter: fc5.bias, gradient: None


No wonder - let's calculate them

In [22]:
loss_tensor.backward()

In [23]:
for name, param in model_MLP.named_parameters():
    print("name of a parameter: {}, gradient: {}".
          format(name, param.grad))

name of a parameter: fc1.weight, gradient: tensor([[ 0.0000e+00,  0.0000e+00,  1.3393e-04,  ...,  1.3313e+00,
         -4.1290e-20,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  3.1685e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00, -2.9847e-08,  ...,  3.7166e-01,
         -7.0487e-20,  0.0000e+00],
        ...,
        [ 0.0000e+00,  0.0000e+00, -3.1952e-04,  ...,  4.8372e-02,
          3.5567e-21,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  5.5135e-09,  ...,  1.0225e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  1.1017e-04,  ..., -8.3645e-01,
         -1.2418e-19,  0.0000e+00]])
name of a parameter: fc1.bias, gradient: tensor([-2.9871e-04,  1.1825e-02,  3.8144e-03,  3.2843e-03, -7.2096e-03,
         4.8469e-03,  4.3653e-03, -6.0873e-04, -1.2929e-03, -1.0235e-02,
        -6.2651e-03, -2.1556e-03, -3.5231e-03,  8.6886e-03,  2.4749e-03,
        -3.2984e-03, -5.7716e-04,  5.5906e-03, -1.4169e-03,  1.08

All we have to do now is subtract the gradient of a given parameter from the parameter tensor itself and do it for all parameters of the model - that should decrease the loss. Normally the gradient is multiplied by a learning rate parameter $\lambda$ so we don't go too far in the loss landscape

In [24]:
lr=0.0001
for param in model_MLP.parameters():
    param.data.add_(-lr*param.grad.data)

call to backward **accumulates** gradients - so we also need to zero the gradient tensors if we want to keep going

In [25]:
for param in model_MLP.parameters():
    param.grad.data.zero_()

There is a much simpler way of doing this - we can use the pytorch [optim](https://pytorch.org/docs/stable/optim.html) classes. This allows us to easily use more advanced optimization options (like momentum or adaptive optimizers like [Adam](https://arxiv.org/abs/1412.6980)):

In [26]:
from torch import optim
optimizer = optim.SGD(model_MLP.parameters(), lr=0.0001)

Lets get a new batch of events

In [27]:
batch1=next(train_iter)

In [28]:
data=batch1[0]
labels=batch1[1]

In [29]:
print(labels)

tensor([0, 1, 1, 1, 1, 0, 0, 1, 1, 2, 0, 1, 1, 1, 0, 1, 2, 0, 1, 1, 2, 2, 0, 2,
        0, 0, 2, 1, 2, 2, 2, 2])


In [30]:
model_out=model_MLP(data)
loss_tensor=loss_module(model_out,labels)
loss_tensor.backward()
optimizer.step()

We could just put the code above in a loop and be done with it, but the usual practice would be to wrap this functionality in a training object. Here we'll use the [engine](/edit/utils/engine.py) class. Let's examine it. We'll talk about:
  1. Implementation of the training loop
  2. Evaluation on validation set and training and test modes.
  3. Turning evaluation of gradients on and off.
  4. Saving and retrieving the model and optimizer state.

In [31]:
from utils.engine import Engine

Let's first create a configuration object -we'll use this to set up our training engine

In [32]:
class CONFIG:
    pass
config=CONFIG()
config.batch_size_test =512
config.batch_size_train = 32
config.batch_size_val = 512
config.lr=0.0001
config.device = 'cpu'
config.num_workers_train=2
config.num_workers_val=1
config.num_workers_test=1
config.dump_path = '../model_state_dumps'


In [33]:
engine=Engine(model_MLP,dset,config)

Sticking to CPU
Creating a directory for run dump: ../model_state_dumps/20240426_100901/


In [34]:
print(vars(config))

{'batch_size_test': 512, 'batch_size_train': 32, 'batch_size_val': 512, 'lr': 0.0001, 'device': 'cpu', 'num_workers_train': 2, 'num_workers_val': 1, 'num_workers_test': 1, 'dump_path': '../model_state_dumps'}


In [ ]:
%%time
engine.train(epochs=1,report_interval=50,valid_interval=100)

Epoch 0 Starting @ 2024-04-26 10:09:03
... Iteration 0 ... Epoch 0.00 ... Validation Loss 32.713 ... Validation Accuracy 0.354
Saved checkpoint as: ../model_state_dumps/20240426_100901/SimpleMLP.pth
best validation loss so far!: 32.712890625
Saved checkpoint as: ../model_state_dumps/20240426_100901/SimpleMLPBEST.pth
... Iteration 1 ... Epoch 0.00 ... Loss 27.706 ... Accuracy 0.375
... Iteration 51 ... Epoch 0.02 ... Loss 1.302 ... Accuracy 0.594
... Iteration 100 ... Epoch 0.04 ... Validation Loss 1.131 ... Validation Accuracy 0.484
Saved checkpoint as: ../model_state_dumps/20240426_100901/SimpleMLP.pth
best validation loss so far!: 1.1314603090286255
Saved checkpoint as: ../model_state_dumps/20240426_100901/SimpleMLPBEST.pth
... Iteration 101 ... Epoch 0.04 ... Loss 0.798 ... Accuracy 0.531
... Iteration 151 ... Epoch 0.06 ... Loss 1.105 ... Accuracy 0.312
... Iteration 200 ... Epoch 0.08 ... Validation Loss 0.950 ... Validation Accuracy 0.512
Saved checkpoint as: ../model_state_dumps

## Defining a simple Convolutional Network

Let's open [simpleCNN](http://localhost:8888/edit/models/simpleCNN.py)

In [5]:
from models.simpleCNN import SimpleCNN
model_CNN=SimpleCNN(num_input_channels=38,num_classes=3)

In [6]:
import numpy as np
def rotate_chan(x):
    return np.transpose(x,(2,0,1))

In [7]:
dset=WCH5Dataset("/scratch/fcormier/Public/NUPRISM.h5",val_split=0.1,test_split=0.1,transform=rotate_chan)

In [8]:
engine=Engine(model_CNN,dset,config)

Sticking to CPU
Creating a directory for run dump: ../model_state_dumps/20240424_223542/


In [9]:
for name, param in model_CNN.named_parameters():
    print("name of a parameter: {}, type: {}, parameter requires a gradient?: {}".
          format(name, type(param),param.requires_grad))

name of a parameter: f_embed.weight, type: <class 'torch.nn.parameter.Parameter'>, parameter requires a gradient?: True
name of a parameter: f_embed.bias, type: <class 'torch.nn.parameter.Parameter'>, parameter requires a gradient?: True
name of a parameter: f_conv1.weight, type: <class 'torch.nn.parameter.Parameter'>, parameter requires a gradient?: True
name of a parameter: f_conv1.bias, type: <class 'torch.nn.parameter.Parameter'>, parameter requires a gradient?: True
name of a parameter: f_conv2a.weight, type: <class 'torch.nn.parameter.Parameter'>, parameter requires a gradient?: True
name of a parameter: f_conv2a.bias, type: <class 'torch.nn.parameter.Parameter'>, parameter requires a gradient?: True
name of a parameter: f_conv2b.weight, type: <class 'torch.nn.parameter.Parameter'>, parameter requires a gradient?: True
name of a parameter: f_conv2b.bias, type: <class 'torch.nn.parameter.Parameter'>, parameter requires a gradient?: True
name of a parameter: f_conv3a.weight, type: 

In [ ]:
#Unfortunately this seems to hang and not train
%%time
engine.train(epochs=5,report_interval=1,valid_interval=10)

Epoch 0 Starting @ 2024-04-24 22:35:47
tensor([[-0.2139,  0.2188,  0.1590],
        [-0.2356,  0.1918,  0.1596]])
... Iteration 0 ... Epoch 0.00 ... Validation Loss 1.004 ... Validation Accuracy 0.000
Saved checkpoint as: ../model_state_dumps/20240424_223542/SimpleCNN.pth
best validation loss so far!: 1.0036206245422363
Saved checkpoint as: ../model_state_dumps/20240424_223542/SimpleCNNBEST.pth
tensor([[-0.2629,  0.2181,  0.2056]], grad_fn=<AddmmBackward0>)
